### ISSUE TITLE
Fails everytime before sharing file list

### ISSUE THREAD

**Issue by aksh1618** [sonudoo/Git-Heat#3]
I'm trying to share a single pdf between two linux machines.

## .config
```
/home/aksh/Documents/Interesting Book.pdf
```

### Server
```
~$ python server.py
Listening on port 23548...
Key exchange successful: 66631762be64e9d927435c357a62a551ed1b70136159ee9aa28452d301045196
Generating Ciphers..
Encrypting File list..
Sending File List..
Client is not ready to receive file list..
Key exchange successful: e95326c712a20dde1c05e8d60e8c90a9e801c474e7a4ff48d9c68d67423f9373
Generating Ciphers..
Encrypting File list..
Sending File List..
Client is not ready to receive file list..
Key exchange successful: 88e73ef0ec89d683e03f3dea80a59d774f6649dec5f8f7b74354a3ffdc4570cc
Generating Ciphers..
Encrypting File list..
Sending File List..
Client is not ready to receive file list..
Key exchange successful: 6d65630d1e6296fefd26cc946d254ed68e7e7b1df210a3a83cef3fb67d316860
Generating Ciphers..
Encrypting File list..
Sending File List..
Client is not ready to receive file list..
^CTraceback (most recent call last):
  File "server.py", line 123, in <module>
    conn, addr = s.accept()
  File "/usr/lib64/python3.6/socket.py", line 205, in accept
    fd, addr = self._accept()
KeyboardInterrupt

~$ python server.py
Listening on port 23548...
Unhandled exception in thread started by <function requestHandler at 0x7f1d9f56fea0>
Traceback (most recent call last):
  File "server.py", line 39, in requestHandler
    dh.generate_shared_secret(clientPublicKey)
  File "/home/aksh/Projects/IET/Git-Heat-submissions/week-4/sonudoo/venv/lib/python3.6/site-packages/diffiehellman/decorators.py", line 39, in func_wrapper
    func(self, *args, **kwargs)
  File "/home/aksh/Projects/IET/Git-Heat-submissions/week-4/sonudoo/venv/lib/python3.6/site-packages/diffiehellman/diffiehellman.py", line 105, in generate_shared_secret
    raise MalformedPublicKey
diffiehellman.exceptions.MalformedPublicKey: Public key malformed: fails Legendre symbol verification.
Unhandled exception in thread started by <function requestHandler at 0x7f1d9f56fea0>
Traceback (most recent call last):
  File "server.py", line 39, in requestHandler
    dh.generate_shared_secret(clientPublicKey)
  File "/home/aksh/Projects/IET/Git-Heat-submissions/week-4/sonudoo/venv/lib/python3.6/site-packages/diffiehellman/decorators.py", line 39, in func_wrapper
    func(self, *args, **kwargs)
  File "/home/aksh/Projects/IET/Git-Heat-submissions/week-4/sonudoo/venv/lib/python3.6/site-packages/diffiehellman/diffiehellman.py", line 105, in generate_shared_secret
    raise MalformedPublicKey
diffiehellman.exceptions.MalformedPublicKey: Public key malformed: fails Legendre symbol verification.
Key exchange successful: 4b4206ffd587196c3b863c41a285dfae4d45badad637cdb02bc7c49f45dc239e
Generating Ciphers..
Encrypting File list..
Sending File List..
Client is not ready to receive file list..
_
```

### Client
```
(githeat) bash-4.4$
(githeat) bash-4.4$ python client.py
Enter the IP address of the server: 192.168.43.79
Key exchange successful: 8f4d123d5832dfc9a1d32f9a30e576bfb8d1becda8857d8ff66f1317d32c91c0                                     Generating Ciphers..
Waiting for file list..
Traceback (most recent call last):
  File "client.py", line 60, in <module>
    s.send("READY".encode('utf-8', errors='ignore'))
ConnectionResetError: [Errno 104] Connection reset by peer
(githeat) bash-4.4$ python client.py
Enter the IP address of the server: 192.168.43.79              
The server sent an illegal response. Closing connection..      
(githeat) bash-4.4$ python client.py
Enter the IP address of the server: 192.168.43.79              
Key exchange successful: c23729619b1219d896c0aac68be53f3e2adb9118b4cf860984a5eef8e7c196c2                                     Generating Ciphers..                                           
Waiting for file list..                                        
The server sent an illegal response. Closing connection..      
(githeat) bash-4.4$ python client.py                           
Enter the IP address of the server: 192.168.43.79              
Key exchange successful: 7094551ba7c57a9c52002353afc3338f58262faeaf8d65f982b3758037f08f96                                     Generating Ciphers..                                           
Waiting for file list..                                        
The server sent an illegal response. Closing connection..      
(githeat) bash-4.4$ python client.py                           
Enter the IP address of the server: 192.168.43.79              
Key exchange successful: 178b9f62df0e5b83b0ab5d15b18772f8a2018d9acab2367b596c70fa06b5dbae                                     Generating Ciphers..                                           
Waiting for file list..                                        
The server sent an illegal response. Closing connection..      
(githeat) bash-4.4$ python client.py                           
Enter the IP address of the server: 192.168.43.79              
Key exchange successful: 0079ba1dc8d793d4eef795a7dbcf35febe2393e7cb482f353ec7c885bc9697fc                                     Generating Ciphers..                                           
Waiting for file list..                                        
The server sent an illegal response. Closing connection..      
(githeat) bash-4.4$ python client.py                           
Enter the IP address of the server: 192.168.43.79              
The server sent an illegal response. Closing connection..

```

**Comment by sonudoo** [comment]
I have added modifications. Please check for the same

**Comment by aksh1618** [comment]
Yes, working now.
